services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: toha62/library-counter:0.0.1
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  library:
    image: toha62/library:0.1.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 80:3000
    environment:
      - PORT=3000      
      - COUNTER_URL=http://counter:3002
    command: npm run dev
    depends_on:      
      - counter
